// Generated by gencpp from file kxr_controller/ServoStateArray.msg
// DO NOT EDIT!


#ifndef KXR_CONTROLLER_MESSAGE_SERVOSTATEARRAY_H
#define KXR_CONTROLLER_MESSAGE_SERVOSTATEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <kxr_controller/ServoState.h>

namespace kxr_controller
{
template <class ContainerAllocator>
struct ServoStateArray_
{
  typedef ServoStateArray_<ContainerAllocator> Type;

  ServoStateArray_()
    : header()
    , servos()  {
    }
  ServoStateArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , servos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::kxr_controller::ServoState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::kxr_controller::ServoState_<ContainerAllocator> >> _servos_type;
  _servos_type servos;





  typedef boost::shared_ptr< ::kxr_controller::ServoStateArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kxr_controller::ServoStateArray_<ContainerAllocator> const> ConstPtr;

}; // struct ServoStateArray_

typedef ::kxr_controller::ServoStateArray_<std::allocator<void> > ServoStateArray;

typedef boost::shared_ptr< ::kxr_controller::ServoStateArray > ServoStateArrayPtr;
typedef boost::shared_ptr< ::kxr_controller::ServoStateArray const> ServoStateArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kxr_controller::ServoStateArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kxr_controller::ServoStateArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kxr_controller::ServoStateArray_<ContainerAllocator1> & lhs, const ::kxr_controller::ServoStateArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.servos == rhs.servos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kxr_controller::ServoStateArray_<ContainerAllocator1> & lhs, const ::kxr_controller::ServoStateArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kxr_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::ServoStateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::ServoStateArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::ServoStateArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::ServoStateArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::ServoStateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::ServoStateArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kxr_controller::ServoStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c49987abc073bf0afcf190de7df7c47c";
  }

  static const char* value(const ::kxr_controller::ServoStateArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc49987abc073bf0aULL;
  static const uint64_t static_value2 = 0xfcf190de7df7c47cULL;
};

template<class ContainerAllocator>
struct DataType< ::kxr_controller::ServoStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kxr_controller/ServoStateArray";
  }

  static const char* value(const ::kxr_controller::ServoStateArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kxr_controller::ServoStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"ServoState[] servos\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: kxr_controller/ServoState\n"
"std_msgs/Header header\n"
"string name\n"
"float64 position\n"
"float64 error\n"
"float64 temperature\n"
"float64 current\n"
;
  }

  static const char* value(const ::kxr_controller::ServoStateArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kxr_controller::ServoStateArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.servos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoStateArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kxr_controller::ServoStateArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kxr_controller::ServoStateArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "servos[]" << std::endl;
    for (size_t i = 0; i < v.servos.size(); ++i)
    {
      s << indent << "  servos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kxr_controller::ServoState_<ContainerAllocator> >::stream(s, indent + "    ", v.servos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KXR_CONTROLLER_MESSAGE_SERVOSTATEARRAY_H
