// Generated by gencpp from file kxr_controller/ServoOnOff.msg
// DO NOT EDIT!


#ifndef KXR_CONTROLLER_MESSAGE_SERVOONOFF_H
#define KXR_CONTROLLER_MESSAGE_SERVOONOFF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kxr_controller
{
template <class ContainerAllocator>
struct ServoOnOff_
{
  typedef ServoOnOff_<ContainerAllocator> Type;

  ServoOnOff_()
    : joint_names()
    , servo_on_states()  {
    }
  ServoOnOff_(const ContainerAllocator& _alloc)
    : joint_names(_alloc)
    , servo_on_states(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _servo_on_states_type;
  _servo_on_states_type servo_on_states;





  typedef boost::shared_ptr< ::kxr_controller::ServoOnOff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kxr_controller::ServoOnOff_<ContainerAllocator> const> ConstPtr;

}; // struct ServoOnOff_

typedef ::kxr_controller::ServoOnOff_<std::allocator<void> > ServoOnOff;

typedef boost::shared_ptr< ::kxr_controller::ServoOnOff > ServoOnOffPtr;
typedef boost::shared_ptr< ::kxr_controller::ServoOnOff const> ServoOnOffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kxr_controller::ServoOnOff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kxr_controller::ServoOnOff_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kxr_controller::ServoOnOff_<ContainerAllocator1> & lhs, const ::kxr_controller::ServoOnOff_<ContainerAllocator2> & rhs)
{
  return lhs.joint_names == rhs.joint_names &&
    lhs.servo_on_states == rhs.servo_on_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kxr_controller::ServoOnOff_<ContainerAllocator1> & lhs, const ::kxr_controller::ServoOnOff_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kxr_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::ServoOnOff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::ServoOnOff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::ServoOnOff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::ServoOnOff_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::ServoOnOff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::ServoOnOff_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kxr_controller::ServoOnOff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29bb8c289c7a237569042d21176cbdd5";
  }

  static const char* value(const ::kxr_controller::ServoOnOff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29bb8c289c7a2375ULL;
  static const uint64_t static_value2 = 0x69042d21176cbdd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::kxr_controller::ServoOnOff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kxr_controller/ServoOnOff";
  }

  static const char* value(const ::kxr_controller::ServoOnOff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kxr_controller::ServoOnOff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] joint_names\n"
"bool[] servo_on_states\n"
;
  }

  static const char* value(const ::kxr_controller::ServoOnOff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kxr_controller::ServoOnOff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_names);
      stream.next(m.servo_on_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoOnOff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kxr_controller::ServoOnOff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kxr_controller::ServoOnOff_<ContainerAllocator>& v)
  {
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "servo_on_states[]" << std::endl;
    for (size_t i = 0; i < v.servo_on_states.size(); ++i)
    {
      s << indent << "  servo_on_states[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.servo_on_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KXR_CONTROLLER_MESSAGE_SERVOONOFF_H
