// Generated by gencpp from file kxr_controller/ServoState.msg
// DO NOT EDIT!


#ifndef KXR_CONTROLLER_MESSAGE_SERVOSTATE_H
#define KXR_CONTROLLER_MESSAGE_SERVOSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kxr_controller
{
template <class ContainerAllocator>
struct ServoState_
{
  typedef ServoState_<ContainerAllocator> Type;

  ServoState_()
    : header()
    , name()
    , position(0.0)
    , error(0.0)
    , temperature(0.0)
    , current(0.0)  {
    }
  ServoState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , position(0.0)
    , error(0.0)
    , temperature(0.0)
    , current(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _position_type;
  _position_type position;

   typedef double _error_type;
  _error_type error;

   typedef double _temperature_type;
  _temperature_type temperature;

   typedef double _current_type;
  _current_type current;





  typedef boost::shared_ptr< ::kxr_controller::ServoState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kxr_controller::ServoState_<ContainerAllocator> const> ConstPtr;

}; // struct ServoState_

typedef ::kxr_controller::ServoState_<std::allocator<void> > ServoState;

typedef boost::shared_ptr< ::kxr_controller::ServoState > ServoStatePtr;
typedef boost::shared_ptr< ::kxr_controller::ServoState const> ServoStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kxr_controller::ServoState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kxr_controller::ServoState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kxr_controller::ServoState_<ContainerAllocator1> & lhs, const ::kxr_controller::ServoState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.position == rhs.position &&
    lhs.error == rhs.error &&
    lhs.temperature == rhs.temperature &&
    lhs.current == rhs.current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kxr_controller::ServoState_<ContainerAllocator1> & lhs, const ::kxr_controller::ServoState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kxr_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::ServoState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::ServoState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::ServoState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::ServoState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::ServoState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::ServoState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kxr_controller::ServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce152110c70fb30775e21de46928de76";
  }

  static const char* value(const ::kxr_controller::ServoState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce152110c70fb307ULL;
  static const uint64_t static_value2 = 0x75e21de46928de76ULL;
};

template<class ContainerAllocator>
struct DataType< ::kxr_controller::ServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kxr_controller/ServoState";
  }

  static const char* value(const ::kxr_controller::ServoState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kxr_controller::ServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string name\n"
"float64 position\n"
"float64 error\n"
"float64 temperature\n"
"float64 current\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kxr_controller::ServoState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kxr_controller::ServoState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.position);
      stream.next(m.error);
      stream.next(m.temperature);
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kxr_controller::ServoState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kxr_controller::ServoState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KXR_CONTROLLER_MESSAGE_SERVOSTATE_H
