// Generated by gencpp from file kxr_controller/Stretch.msg
// DO NOT EDIT!


#ifndef KXR_CONTROLLER_MESSAGE_STRETCH_H
#define KXR_CONTROLLER_MESSAGE_STRETCH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kxr_controller
{
template <class ContainerAllocator>
struct Stretch_
{
  typedef Stretch_<ContainerAllocator> Type;

  Stretch_()
    : joint_names()
    , stretch()  {
    }
  Stretch_(const ContainerAllocator& _alloc)
    : joint_names(_alloc)
    , stretch(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _stretch_type;
  _stretch_type stretch;





  typedef boost::shared_ptr< ::kxr_controller::Stretch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kxr_controller::Stretch_<ContainerAllocator> const> ConstPtr;

}; // struct Stretch_

typedef ::kxr_controller::Stretch_<std::allocator<void> > Stretch;

typedef boost::shared_ptr< ::kxr_controller::Stretch > StretchPtr;
typedef boost::shared_ptr< ::kxr_controller::Stretch const> StretchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kxr_controller::Stretch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kxr_controller::Stretch_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kxr_controller::Stretch_<ContainerAllocator1> & lhs, const ::kxr_controller::Stretch_<ContainerAllocator2> & rhs)
{
  return lhs.joint_names == rhs.joint_names &&
    lhs.stretch == rhs.stretch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kxr_controller::Stretch_<ContainerAllocator1> & lhs, const ::kxr_controller::Stretch_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kxr_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::Stretch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::Stretch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::Stretch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::Stretch_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::Stretch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::Stretch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kxr_controller::Stretch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b2b730aeb11dca161b5a118a2171acb";
  }

  static const char* value(const ::kxr_controller::Stretch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b2b730aeb11dca1ULL;
  static const uint64_t static_value2 = 0x61b5a118a2171acbULL;
};

template<class ContainerAllocator>
struct DataType< ::kxr_controller::Stretch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kxr_controller/Stretch";
  }

  static const char* value(const ::kxr_controller::Stretch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kxr_controller::Stretch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] joint_names\n"
"int32[] stretch\n"
;
  }

  static const char* value(const ::kxr_controller::Stretch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kxr_controller::Stretch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_names);
      stream.next(m.stretch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Stretch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kxr_controller::Stretch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kxr_controller::Stretch_<ContainerAllocator>& v)
  {
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "stretch[]" << std::endl;
    for (size_t i = 0; i < v.stretch.size(); ++i)
    {
      s << indent << "  stretch[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.stretch[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KXR_CONTROLLER_MESSAGE_STRETCH_H
