arm_controller: 
  type: effort_controllers/JointTrajectoryController
  joints:
    - 1st_joint
    - 2nd_joint
    - 3rd_joint
    - 4th_joint
    - 5th_joint
    - 6th_joint
  gains:
    1st_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    2nd_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    3rd_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    4th_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    5th_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    6th_joint: {p: 100, d: 1, i: 1, i_clamp: 1}

joint_state_controller: 
  type: joint_state_controller/JointStateController
  publish_rate: 50