controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1: {p: 100.0, i: 0.01, d: 10.0}
      joint2: {p: 100.0, i: 0.01, d: 10.0}
      joint3: {p: 100.0, i: 0.01, d: 10.0}
      joint4: {p: 100.0, i: 0.01, d: 10.0}
      joint5: {p: 100.0, i: 0.01, d: 10.0}
      joint6: {p: 100.0, i: 0.01, d: 10.0}
initial:  # Define initial robot poses per group
  - group: arm
    pose: home