joint_name_to_servo_id: {
  1st_joint: {id: 2, direction: 1, offset: 0},
  2nd_joint: {id: 4, direction: 1, offset: 0},
  3rd_joint: {id: 6, direction: 1, offset: 0},
  4th_joint: {id: 8, direction: 1, offset: 0},
  5th_joint: {id: 10, direction: 1, offset: 0},
  6th_joint: {id: 12, direction: 1, offset: 0}
}