; Auto-generated. Do not edit!


(cl:in-package kxr_controller-msg)


;//! \htmlinclude AdjustAngleVectorResult.msg.html

(cl:defclass <AdjustAngleVectorResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass AdjustAngleVectorResult (<AdjustAngleVectorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AdjustAngleVectorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AdjustAngleVectorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kxr_controller-msg:<AdjustAngleVectorResult> is deprecated: use kxr_controller-msg:AdjustAngleVectorResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AdjustAngleVectorResult>) ostream)
  "Serializes a message object of type '<AdjustAngleVectorResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AdjustAngleVectorResult>) istream)
  "Deserializes a message object of type '<AdjustAngleVectorResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AdjustAngleVectorResult>)))
  "Returns string type for a message object of type '<AdjustAngleVectorResult>"
  "kxr_controller/AdjustAngleVectorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AdjustAngleVectorResult)))
  "Returns string type for a message object of type 'AdjustAngleVectorResult"
  "kxr_controller/AdjustAngleVectorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AdjustAngleVectorResult>)))
  "Returns md5sum for a message object of type '<AdjustAngleVectorResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AdjustAngleVectorResult)))
  "Returns md5sum for a message object of type 'AdjustAngleVectorResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AdjustAngleVectorResult>)))
  "Returns full string definition for message of type '<AdjustAngleVectorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AdjustAngleVectorResult)))
  "Returns full string definition for message of type 'AdjustAngleVectorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AdjustAngleVectorResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AdjustAngleVectorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'AdjustAngleVectorResult
))
