; Auto-generated. Do not edit!


(cl:in-package kxr_controller-msg)


;//! \htmlinclude AdjustAngleVectorFeedback.msg.html

(cl:defclass <AdjustAngleVectorFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass AdjustAngleVectorFeedback (<AdjustAngleVectorFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AdjustAngleVectorFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AdjustAngleVectorFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kxr_controller-msg:<AdjustAngleVectorFeedback> is deprecated: use kxr_controller-msg:AdjustAngleVectorFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AdjustAngleVectorFeedback>) ostream)
  "Serializes a message object of type '<AdjustAngleVectorFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AdjustAngleVectorFeedback>) istream)
  "Deserializes a message object of type '<AdjustAngleVectorFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AdjustAngleVectorFeedback>)))
  "Returns string type for a message object of type '<AdjustAngleVectorFeedback>"
  "kxr_controller/AdjustAngleVectorFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AdjustAngleVectorFeedback)))
  "Returns string type for a message object of type 'AdjustAngleVectorFeedback"
  "kxr_controller/AdjustAngleVectorFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AdjustAngleVectorFeedback>)))
  "Returns md5sum for a message object of type '<AdjustAngleVectorFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AdjustAngleVectorFeedback)))
  "Returns md5sum for a message object of type 'AdjustAngleVectorFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AdjustAngleVectorFeedback>)))
  "Returns full string definition for message of type '<AdjustAngleVectorFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AdjustAngleVectorFeedback)))
  "Returns full string definition for message of type 'AdjustAngleVectorFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AdjustAngleVectorFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AdjustAngleVectorFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AdjustAngleVectorFeedback
))
