; Auto-generated. Do not edit!


(cl:in-package kxr_controller-msg)


;//! \htmlinclude PressureControlFeedback.msg.html

(cl:defclass <PressureControlFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PressureControlFeedback (<PressureControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PressureControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PressureControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kxr_controller-msg:<PressureControlFeedback> is deprecated: use kxr_controller-msg:PressureControlFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PressureControlFeedback>) ostream)
  "Serializes a message object of type '<PressureControlFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PressureControlFeedback>) istream)
  "Deserializes a message object of type '<PressureControlFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PressureControlFeedback>)))
  "Returns string type for a message object of type '<PressureControlFeedback>"
  "kxr_controller/PressureControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PressureControlFeedback)))
  "Returns string type for a message object of type 'PressureControlFeedback"
  "kxr_controller/PressureControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PressureControlFeedback>)))
  "Returns md5sum for a message object of type '<PressureControlFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PressureControlFeedback)))
  "Returns md5sum for a message object of type 'PressureControlFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PressureControlFeedback>)))
  "Returns full string definition for message of type '<PressureControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PressureControlFeedback)))
  "Returns full string definition for message of type 'PressureControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PressureControlFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PressureControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PressureControlFeedback
))
