; Auto-generated. Do not edit!


(cl:in-package kxr_controller-msg)


;//! \htmlinclude PressureControlResult.msg.html

(cl:defclass <PressureControlResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PressureControlResult (<PressureControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PressureControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PressureControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kxr_controller-msg:<PressureControlResult> is deprecated: use kxr_controller-msg:PressureControlResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PressureControlResult>) ostream)
  "Serializes a message object of type '<PressureControlResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PressureControlResult>) istream)
  "Deserializes a message object of type '<PressureControlResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PressureControlResult>)))
  "Returns string type for a message object of type '<PressureControlResult>"
  "kxr_controller/PressureControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PressureControlResult)))
  "Returns string type for a message object of type 'PressureControlResult"
  "kxr_controller/PressureControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PressureControlResult>)))
  "Returns md5sum for a message object of type '<PressureControlResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PressureControlResult)))
  "Returns md5sum for a message object of type 'PressureControlResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PressureControlResult>)))
  "Returns full string definition for message of type '<PressureControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PressureControlResult)))
  "Returns full string definition for message of type 'PressureControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PressureControlResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PressureControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PressureControlResult
))
