; Auto-generated. Do not edit!


(cl:in-package kxr_controller-msg)


;//! \htmlinclude ServoOnOffResult.msg.html

(cl:defclass <ServoOnOffResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ServoOnOffResult (<ServoOnOffResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ServoOnOffResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ServoOnOffResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kxr_controller-msg:<ServoOnOffResult> is deprecated: use kxr_controller-msg:ServoOnOffResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ServoOnOffResult>) ostream)
  "Serializes a message object of type '<ServoOnOffResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ServoOnOffResult>) istream)
  "Deserializes a message object of type '<ServoOnOffResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ServoOnOffResult>)))
  "Returns string type for a message object of type '<ServoOnOffResult>"
  "kxr_controller/ServoOnOffResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ServoOnOffResult)))
  "Returns string type for a message object of type 'ServoOnOffResult"
  "kxr_controller/ServoOnOffResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ServoOnOffResult>)))
  "Returns md5sum for a message object of type '<ServoOnOffResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ServoOnOffResult)))
  "Returns md5sum for a message object of type 'ServoOnOffResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ServoOnOffResult>)))
  "Returns full string definition for message of type '<ServoOnOffResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ServoOnOffResult)))
  "Returns full string definition for message of type 'ServoOnOffResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ServoOnOffResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ServoOnOffResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ServoOnOffResult
))
