; Auto-generated. Do not edit!


(cl:in-package kxr_controller-msg)


;//! \htmlinclude ServoOnOffFeedback.msg.html

(cl:defclass <ServoOnOffFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ServoOnOffFeedback (<ServoOnOffFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ServoOnOffFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ServoOnOffFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kxr_controller-msg:<ServoOnOffFeedback> is deprecated: use kxr_controller-msg:ServoOnOffFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ServoOnOffFeedback>) ostream)
  "Serializes a message object of type '<ServoOnOffFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ServoOnOffFeedback>) istream)
  "Deserializes a message object of type '<ServoOnOffFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ServoOnOffFeedback>)))
  "Returns string type for a message object of type '<ServoOnOffFeedback>"
  "kxr_controller/ServoOnOffFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ServoOnOffFeedback)))
  "Returns string type for a message object of type 'ServoOnOffFeedback"
  "kxr_controller/ServoOnOffFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ServoOnOffFeedback>)))
  "Returns md5sum for a message object of type '<ServoOnOffFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ServoOnOffFeedback)))
  "Returns md5sum for a message object of type 'ServoOnOffFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ServoOnOffFeedback>)))
  "Returns full string definition for message of type '<ServoOnOffFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ServoOnOffFeedback)))
  "Returns full string definition for message of type 'ServoOnOffFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ServoOnOffFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ServoOnOffFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ServoOnOffFeedback
))
