; Auto-generated. Do not edit!


(cl:in-package kxr_controller-msg)


;//! \htmlinclude StretchFeedback.msg.html

(cl:defclass <StretchFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StretchFeedback (<StretchFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StretchFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StretchFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kxr_controller-msg:<StretchFeedback> is deprecated: use kxr_controller-msg:StretchFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StretchFeedback>) ostream)
  "Serializes a message object of type '<StretchFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StretchFeedback>) istream)
  "Deserializes a message object of type '<StretchFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StretchFeedback>)))
  "Returns string type for a message object of type '<StretchFeedback>"
  "kxr_controller/StretchFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StretchFeedback)))
  "Returns string type for a message object of type 'StretchFeedback"
  "kxr_controller/StretchFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StretchFeedback>)))
  "Returns md5sum for a message object of type '<StretchFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StretchFeedback)))
  "Returns md5sum for a message object of type 'StretchFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StretchFeedback>)))
  "Returns full string definition for message of type '<StretchFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StretchFeedback)))
  "Returns full string definition for message of type 'StretchFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StretchFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StretchFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StretchFeedback
))
